---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

stages:
  - build

build:
  image: ${CI_REGISTRY}/clearsy-public/bbatch-linux-docker/debian-11
  stage: build
  tags:
    - docker
    - linux
  script:
    - mkdir -p build
    - cd build
    - cmake -G Ninja ..
    - cmake --build .
    - ctest
    - cd ..
  artifacts:
    paths:
      - build/Testing/Temporary/LastTest.log
    when: always
    expire_in: 1 week
