variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

build:
  image: ${CI_REGISTRY}/clearsy-public/bbatch-linux-docker/ubuntu-24.04
  tags:
    - docker
    - linux
  stage: build
  script:
    - cmake -B build
    - cmake --build build
    - cd build
    - ctest
  artifacts:
    paths:
      - build/Testing/Temporary/LastTest.log
    when: always
    expire_in: 1 month
