name: Clang Format Checker
on: [push, pull_request]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "src/pog2smtlib-2.7/**/*.h,src/pog2smtlib-2.7/**/*.cpp"
          style: file
